### ISSUE TITLE
CSS from userstyles.org via Stylish and UserScripts combo

### ISSUE THREAD

**Issue by Martii** [JasonBarnabe/userstyles#80]
So I have a possible detected issue... the CSS on userstyles [here](https://userstyles.org/styles/121057/facebook-flat-by-chewbaka) and the .user.js [here](https://openuserjs.org/scripts/chewbaka/facebook_flat) *(which)* has a  `readCookie` function... with CSS `content` do you see if there is a security risk with having both of these running? The function itself doesn't appear to be called in the .user.js but it is a little unusual. Since I don't use Stylish I was hoping for a little insight if there is a vulnerability. 

It might be possible to have a third script that would utilize this as an exploit since it is `@grant none`... but I don't think it's on OUJS that I'm aware of... might want to check GreasyFork for a possible presence from this author.

Clip from the CSS
``` css
body ._li::before { ",
	"      content: \"<p>234324<\/p>\";",
```
Clip from the .user.js

``` js
function readCookie(name) {
  var nameEQ = name + '=';
  var ca = document.cookie.split(';');
  for (var i = 0; i < ca.length; i++) {
    var c = ca[i];
    while (c.charAt(0) == ' ') c = c.substring(1, c.length);
    if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length, c.length);
  }
  return null;
}
```

TIA

**Comment by JasonBarnabe** [comment]
Thanks for reporting.

I don't think [CSS content](https://developer.mozilla.org/en/docs/Web/CSS/content) can be HTML (and so you couldn't for example include a `script` tag), so I don't see how this is a potential vulnerability. If you're thinking there's some other vector than XSS via the CSS `content`, please explain further.

**Comment by Martii** [comment]
Well on USO we had Phasma who liked to combine multipe .user.js into auto-liking scripts and other exploits. So not necessarily XSS.

Since this script is targeted at Facebook *(FB)*... those scripts always get extra scrutiny... and the CSS rule has a possible signature to FB auto-liking with their numbering system.

Doing speculation here...

It doesn't necessarily have to be a element node but with a text node you can read that in with [`DOMParser`](https://developer.mozilla.org/docs/Web/API/DOMParser), take the cookie that is read in from this content-scoped function and in a n<sup>th</sup> .user.js craft a URL or POST request, with whatever security token FB generates... that could auto-like *(or auto-anything)* with that potential FB id. This might be a stretch but I do look for possible things like this as Admin over on our site... obviously I can approach that user but I thought I'd get some more intel first.

**Comment by Martii** [comment]
This could also be achieved directly with XPath and/or `querySelector` and `innerHTML` ... find the class, take that value and put it somewhere whether an identifier or web storage, destroy the text node, then resume crafting the URL or POST request. It could be so abstracted that it could be difficult to detect especially if there is a third .user.js involved.

**Comment by JasonBarnabe** [comment]
Sure, a user script could read in the `content` set by a user style, but I don't think this would accomplish much. You could detect that the style is installed and what it does, but `content` has less access to the page than what the script would have, so I don't see any problem there.

I mean, maybe you could use this to obfuscate what a script is doing, for example by putting JS code in the `content` and having a script read that and then execute it, but it seems pretty unlikely that someone would do this because it would require both a user style and a user script to be installed for this to work. And even then, there's a few red flags on both sides that could be found be a moderator on whatever site.

I don't see anything nefarious in the example you provided. It just looks like the author thought he could put HTML in `content`, and also included some library functions in the script. But I will keep an eye out for anything odd in other scripts and styles.
